name: df-env
channels:
  - pytorch
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - datasets
  - ipykernel
  - jupyter
  - matplotlib
  - nb_conda_kernels
  - numpy
  - opencv
  - pyarrow
  - python=3.10
  - conda-forge::pytorch-lightning
  - transformers
  - pytorch::pytorch-cuda
  - pytorch::pytorch
  - pytorch::torchvision
  - timm
prefix: /home/FYP/tanj0303/.conda/envs/df-env
