name: df-env
channels:
  - conda-forge
dependencies:
  - conda-forge::pytorch-lightning
  - datasets
  - ipykernel
  - jupyter
  - matplotlib
  - nb_conda_kernels
  - numpy
  - opencv
  - pyarrow
  - python=3.12
  # - pytorch::pytorch-cuda
  - pytorch::torchvision
  - transformers
  - pytorch::pytorch
  - conda-forge::pywavelets
  - timm
prefix: /home/FYP/tanj0303/.conda/envs/df-env
