name: df-env
channels:
  - conda-forge
dependencies:
  - datasets
  - flask
  - flask-cors
  - ipykernel
  - jupyter
  - matplotlib
  - nb_conda_kernels
  - numpy
  - opencv
  - pyarrow
  - python=3.12
  # - pytorch::pytorch-cuda
  - pytorch::pytorch
  - pytorch-lightning
  - pywavelets
  - pytorch::torchvision
  - scikit-learn
  - transformers
  - timm
prefix: /home/FYP/tanj0303/.conda/envs/df-env
